import React from 'react';
import Sidebar from '@/components/layout/sidebar'
import MobileNav from '@/components/layout/mobile-nav'
import Footer from '@/components/footer'
import Header from '@/components/header'
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="w-full">
        <Header />
        <div className="flex min-h-screen">
          <Sidebar />
          <div className="flex-1 flex flex-col pb-20 lg:pb-0">
            {children}
            <Footer />
          </div>
          <MobileNav />
        </div>
        </div>
      </body>
    </html>
  )
}